version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - ./db-data/pg:/var/lib/postgresql/data
    container_name: postgres
    environment:
      TZ: Asia/Tehran
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
  crawler:
    build:
       context: .
       dockerfile: './Dockerfile'
    image: 'crawler:1.0.0'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  celery_worker:
    container_name: 'celery_worker'
    image: 'crawler:1.0.0'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    command: >
      /bin/sh -c "
      while ! nc -z crawler 8000;
      do
      echo waiting for crawler app;
      sleep 3;
      done;
      echo Connected!;
      python -m celery -A RssCrawler worker -l error
      "
    depends_on:
      - crawler
      - redis
  celery_beat:
    container_name: 'celery_beat'
    image: 'crawler:1.0.0'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    command: >
      /bin/sh -c "
      while ! nc -z crawler 8000;
      do
      echo waiting for crawler app;
      sleep 3;
      done;
      echo Connected!;
      python -m celery -A RssCrawler beat -l error
      "
    depends_on:
      - crawler
      - redis
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./db-data/redis:/data